# Site settings
title: CSCE 580
subtitle: Artificial Intelligence (Under Construction)
email: pjamshid@cse.sc.edu
description: "This course will introduce the basic ideas and techniques underlying the design of intelligent computer-based systems. As opposed to a traditional logic-based artificial intelligence (AI) course, a specific emphasis will be on statistical inference and machine learning."
learning_goals: "Learning goals include: (i) Underestanding classical as well as recently discovered methods in AI, and explore their potential applications. (ii) Building AI systems that autonomously make decision and act not only in fully informed environments, but also in partially observable and adversarial contexts. (iii) Building AI systems that make probabilistic inferences in uncertain and dynamic environments."

class_hours: "TR 4:25 - 5:40pm"
classroom: "300 Main St. B213"
office_hours: "TR 3 - 4pm"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pooyanjamshidi.github.io/csce580/" # the base hostname & protocol for your site
twitter_username: pooyanjamshidi
github_username: pooyanjamshidi
leadimage: ai-photo1.jpg
leadimage_description: "Welcome to CSCE 580: Artificial Intelligence"
authorurl: "https://pooyanjamshidi.github.io"
syllabus: "https://github.com/pooyanjamshidi/mls/blob/master/syllabus/mls.pdf"
githublink: "https://github.com/pooyanjamshidi/csce580"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

include: ['_images']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
