# Site settings
title: CSCE 580
subtitle: Artificial Intelligence
email: pjamshid@cse.sc.edu
description: "This course will introduce the basic ideas and techniques underlying the design of intelligent computer systems. A specific emphasis will be on the statistical and decision-theoretic modeling paradigm."
class_hours: "TR 4:25 - 5:40pm"
office_hours: "TR 3-4pm"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pooyanjamshidi.github.io/csce580/" # the base hostname & protocol for your site
twitter_username: pooyanjamshidi
github_username: pooyanjamshidi
leadimage: ai-photo1.jpg
leadimage_description: "Welcome to CSCE 580: Artificial Intelligence"
authorurl: "https://pooyanjamshidi.github.io"
syllabus: "https://github.com/pooyanjamshidi/mls/blob/master/syllabus/mls.pdf"
githublink: "https://github.com/pooyanjamshidi/csce580"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

include: ['_images']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
